//HintName: ArcadeModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public static partial class ArcadeModule
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "arcade";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionManual(args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out int a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 2, out int a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::ArcadeModule.AddScore(a1, a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("add_score", __var0);
        module.Set("difficulty", (double)global::ArcadeModule.Difficulty);
        module.Set("tokens", global::ArcadeModule.Tokens);
    }
}
