//HintName: NetModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public static partial class NetModule
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "net";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
            return global::Darp.Luau.LuauReturn.Await(
                new global::System.Threading.Tasks.ValueTask<string>(global::NetModule.FetchAsync(a1, args.CancellationToken)),
                static returns => global::Darp.Luau.LuauReturn.Ok(returns)
            );
        });
        module.Set("fetch", __var0);
    }
}
