//HintName: NamesModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public static partial class NamesModule
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "names";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionManual(args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out int a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::NamesModule.@return(a1);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("give_back", __var0);
        module.Set("module", global::NamesModule.module);
        module.Set("state", global::NamesModule.state);
    }
}
