//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.6c68102cb9a313c4.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<global::System.Threading.Tasks.Task<global::Darp.Luau.LuauValue>> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            return awaiter.Await(
                new global::System.Threading.Tasks.ValueTask<global::Darp.Luau.LuauValue>(onLuaCall()),
                static returns =>
                {
                    try
                    {
                        return global::Darp.Luau.LuauReturn.Ok(returns);
                    }
                    finally
                    {
                        returns.Dispose();
                    }
                }
            );
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
