//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.a80a0f922576143d.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<global::Darp.Luau.LuauValue, global::Darp.Luau.LuauValue> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionManual(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            global::Darp.Luau.LuauValue a1 = default;
            try
            {
                if (!args.TryReadLuauValue(parameterIndex: 1, out a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = onLuaCall(a1);
                try
                {
                    return global::Darp.Luau.LuauReturn.Ok(returns);
                }
                finally
                {
                    returns.Dispose();
                }
            }
            finally
            {
                a1.Dispose();
            }
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
