//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.445a7abee97904e3.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<global::Darp.Luau.LuauValue, global::System.Threading.Tasks.Task> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionManual(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            global::Darp.Luau.LuauValue a1 = default;
            bool isHandedOver = false;
            try
            {
                if (!args.TryReadLuauValue(parameterIndex: 1, out a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var pending = new global::System.Threading.Tasks.ValueTask(onLuaCall(a1));
                isHandedOver = true;
                return awaiter.Await(ReleaseAfter(pending, a1));
            }
            finally
            {
                if (!isHandedOver)
                {
                    a1.Dispose();
                }
            }

            static async global::System.Threading.Tasks.ValueTask<global::Darp.Luau.LuauReturn> ReleaseAfter(global::System.Threading.Tasks.ValueTask pending, global::Darp.Luau.LuauValue a1)
            {
                try
                {
                    await pending;
                    return global::Darp.Luau.LuauReturn.Ok();
                }
                finally
                {
                    a1.Dispose();
                }
            }
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
