//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.8e17485680a6f5e3.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<int,global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out double a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            int a1 = (int)a1Raw;
            return global::Darp.Luau.LuauReturn.Await(Complete(onLuaCall(a1, args.CancellationToken)));
            
            static async global::System.Threading.Tasks.ValueTask<global::Darp.Luau.LuauReturn> Complete(global::System.Threading.Tasks.Task pending)
            {
                await pending;
                return global::Darp.Luau.LuauReturn.Ok();
            }
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
