<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Darp.Luau.Generator</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" Version="5.0.0-preview.2" />
    <PackageReference Include="xunit.v3.aot" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Darp.Luau\Darp.Luau.csproj" />
    <ProjectReference
      Include="..\..\src\Darp.Luau.Generator\Darp.Luau.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>

  <ItemGroup>
    <None Include="Require/scripts/**/*" Pack="true" PackagePath="Require/scripts/" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
