//HintName: Amount.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Amount : global::Darp.Luau.ILuauUserdata<global::Amount>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Amount>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Amount> registry)
    {
        registry.TypeName = "Amount";
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Add, static args =>
        {
            if (args.IsUserdata<global::Amount>(1) && args.IsUserdata<global::Amount>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 2, out global::Amount? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 + a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (add) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Div, static args =>
        {
            if (args.IsUserdata<global::Amount>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Number)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 2, out double a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 / a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (div) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Eq, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 2, out global::Amount? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 == a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Le, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 2, out global::Amount? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 <= a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Lt, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 2, out global::Amount? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 < a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Mod, static args =>
        {
            if (args.IsUserdata<global::Amount>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Number)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 2, out double a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 % a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (mod) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Mul, static args =>
        {
            if (args.IsUserdata<global::Amount>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Number)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 2, out double a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 * a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (mul) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Sub, static args =>
        {
            if (args.IsUserdata<global::Amount>(1) && args.IsUserdata<global::Amount>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Amount>(parameterIndex: 2, out global::Amount? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 - a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (sub) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Unm, static args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Amount>(parameterIndex: 1, out global::Amount? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (-a1);
            return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
        });
    }
}
