//HintName: Reversed.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Reversed : global::Darp.Luau.ILuauUserdata<global::Reversed>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Reversed>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Reversed> registry)
    {
        registry.TypeName = "Reversed";
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Eq, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Reversed>(parameterIndex: 1, out global::Reversed? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Reversed>(parameterIndex: 2, out global::Reversed? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 != a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Le, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Reversed>(parameterIndex: 1, out global::Reversed? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Reversed>(parameterIndex: 2, out global::Reversed? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 >= a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Lt, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Reversed>(parameterIndex: 1, out global::Reversed? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Reversed>(parameterIndex: 2, out global::Reversed? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 > a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
    }
}
