//HintName: Player.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Player : global::Darp.Luau.ILuauUserData<global::Player>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauReturnSingle OnIndex(global::Player self, in global::Darp.Luau.LuauState state, in global::System.ReadOnlySpan<char> fieldName)
    {
        return fieldName switch
        {
            "kind" => global::Darp.Luau.LuauReturnSingle.Ok(self.@class),
            "level" => global::Darp.Luau.LuauReturnSingle.Ok(self.Level),
            _ => global::Darp.Luau.LuauReturnSingle.NotHandled,
        };
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauOutcome OnSetIndex(global::Player self, global::Darp.Luau.LuauArgsSingle args, in global::System.ReadOnlySpan<char> fieldName)
    {
        switch (fieldName)
        {
            case "kind":
            {
                if (!args.TryReadNumber(out double valueRaw, out string? error))
                    return global::Darp.Luau.LuauOutcome.Error(error);
                int value = (int)valueRaw;
                self.@class = value;
                return global::Darp.Luau.LuauOutcome.Ok();
            }
            case "level":
            {
                return global::Darp.Luau.LuauOutcome.Error("userdata member 'level' is read-only");
            }
            default:
                return global::Darp.Luau.LuauOutcome.NotHandledError;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauReturn OnMethodCall(global::Player self, global::Darp.Luau.LuauArgs args, in global::System.ReadOnlySpan<char> methodName)
    {
        switch (methodName)
        {
            case "fallback":
            {
                if (!args.TryValidateArgumentCount(1, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 1, out double a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                int a1 = (int)a1Raw;
                var returns = self.@default(a1);
                return global::Darp.Luau.LuauReturn.Ok(returns);
            }
            default:
                return global::Darp.Luau.LuauReturn.NotHandledError;
        }
    }
}
