//HintName: Coin.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Coin : global::Darp.Luau.ILuauUserdata<global::Coin>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Coin>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Coin> registry)
    {
        registry.TypeName = "Coin";
    }
}
