//HintName: Bag.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Bag : global::Darp.Luau.ILuauUserdata<global::Bag>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Bag>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Bag> registry)
    {
        registry.TypeName = "Bag";
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Add, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.IsUserdata<global::Bag>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 2, out global::Bag? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Add(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            if (args.IsUserdata<global::Bag>(1) && args.IsUserdata<global::Coin>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Coin>(parameterIndex: 2, out global::Coin? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Add(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (add) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Concat, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.String)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 2, out global::System.ReadOnlySpan<byte> a2Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a2 = global::System.Text.Encoding.UTF8.GetString(a2Raw);
                var returns = a1.Join(a2);
                return global::Darp.Luau.LuauReturn.Ok(returns);
            }
            if (args.GetValueType(1) is global::Darp.Luau.LuauValueType.String && args.IsUserdata<global::Bag>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 2, out global::Bag? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = global::Bag.Join(a1, a2);
                return global::Darp.Luau.LuauReturn.Ok(returns);
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to concatenate {args.GetTypeName(1)} with {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Div, static args =>
        {
            if (args.IsUserdata<global::Bag>(1))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                global::Darp.Luau.LuauValue a2 = default;
                try
                {
                    if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    if (!args.TryReadLuauValue(parameterIndex: 2, out a2, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    var returns = a1.Share(a2);
                    return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
                }
                finally
                {
                    a2.Dispose();
                }
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (div) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.IDiv, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && (args.GetValueType(2) is global::Darp.Luau.LuauValueType.Number || args.GetValueType(2) is global::Darp.Luau.LuauValueType.Nil))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumberOrNil(parameterIndex: 2, out double? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Split(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (idiv) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Mod, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Function)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadLuauFunction(parameterIndex: 2, out global::Darp.Luau.LuauFunctionView a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Keep(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (mod) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Mul, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Userdata)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadLuauUserdata(parameterIndex: 2, out global::Darp.Luau.LuauUserdataView a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Merge(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (mul) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.NewIndex, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.String && args.GetValueType(3) is global::Darp.Luau.LuauValueType.Number)
            {
                if (!args.TryValidateArgumentCount(3, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 2, out global::System.ReadOnlySpan<byte> a2Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a2 = global::System.Text.Encoding.UTF8.GetString(a2Raw);
                if (!args.TryReadNumber(parameterIndex: 3, out double a3, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                a1.Put(a2, a3);
                return global::Darp.Luau.LuauReturn.Ok();
            }
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Number && args.GetValueType(3) is global::Darp.Luau.LuauValueType.Number)
            {
                if (!args.TryValidateArgumentCount(3, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 2, out int a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 3, out double a3, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                a1.Put(a2, a3);
                return global::Darp.Luau.LuauReturn.Ok();
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to set a userdata member with a {args.GetTypeName(2)} key and a {args.GetTypeName(3)} value");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Pow, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Buffer)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadLuauBuffer(parameterIndex: 2, out global::Darp.Luau.LuauBufferView a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Fill(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (pow) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Sub, static args =>
        {
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Boolean)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadBoolean(parameterIndex: 2, out bool a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Without(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            if (args.IsUserdata<global::Bag>(1) && args.GetValueType(2) is global::Darp.Luau.LuauValueType.Table)
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bag>(parameterIndex: 1, out global::Bag? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadLuauTable(parameterIndex: 2, out global::Darp.Luau.LuauTableView a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = a1.Without(a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (sub) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
    }
}
