//HintName: Bits.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Bits : global::Darp.Luau.ILuauUserdata<global::Bits>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Bits>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Bits> registry)
    {
        registry.TypeName = "Bits";
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Concat, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 & a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to concatenate {args.GetTypeName(1)} with {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Div, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 / a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (div) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Eq, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 == a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.IDiv, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 | a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (idiv) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Le, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 <= a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Len, static args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (+a1);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Lt, static args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (a1 < a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Mod, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 % a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (mod) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Mul, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 * a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (mul) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Pow, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 ^ a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (pow) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Sub, static args =>
        {
            if (args.IsUserdata<global::Bits>(1) && args.IsUserdata<global::Bits>(2))
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::Bits>(parameterIndex: 2, out global::Bits? a2, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = (a1 - a2);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            }
            return global::Darp.Luau.LuauReturn.Error($"attempt to perform arithmetic (sub) on {args.GetTypeName(1)} and {args.GetTypeName(2)}");
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.ToString, static args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (!a1);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddMetamethod(global::Darp.Luau.LuauMetamethod.Unm, static args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUserdata<global::Bits>(parameterIndex: 1, out global::Bits? a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = (~a1);
            return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
        });
    }
}
