//HintName: Player.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Player : global::Darp.Luau.ILuauUserdata<global::Player>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Player>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Player> registry)
    {
        registry.TypeName = "Player";
        registry.AddMethod("fallback", static (self, args) =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out int a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = self.@default(a1);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        registry.AddGetter("kind", static (self, _) => global::Darp.Luau.LuauReturnSingle.Ok(self.@class));
        registry.AddSetter("kind", static (self, args) =>
        {
            if (!args.TryReadNumber(out int value, out string? error))
                return global::Darp.Luau.LuauOutcome.Error(error);
            self.@class = value;
            return global::Darp.Luau.LuauOutcome.Ok();
        });
        registry.AddGetter("level", static (self, _) => global::Darp.Luau.LuauReturnSingle.Ok(self.Level));
    }
}
