//HintName: event.class.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

namespace @event
{
    public sealed partial class @class : global::Darp.Luau.ILuauUserdata<global::@event.@class>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
        static void global::Darp.Luau.ILuauUserdata<global::@event.@class>.Register(global::Darp.Luau.LuauUserdataRegistry<global::@event.@class> registry)
        {
            registry.TypeName = "class";
            registry.AddGetter("level", static (self, _) => global::Darp.Luau.LuauReturnSingle.Ok(self.Level));
            registry.AddSetter("level", static (self, args) =>
            {
                if (!args.TryReadNumber(out int value, out string? error))
                    return global::Darp.Luau.LuauOutcome.Error(error);
                self.Level = value;
                return global::Darp.Luau.LuauOutcome.Ok();
            });
        }
    }
}
