//HintName: event.class.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

namespace @event
{
    public sealed partial class @class : global::Darp.Luau.ILuauUserData<global::@event.@class>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
        public static global::Darp.Luau.LuauReturnSingle OnIndex(global::@event.@class self, in global::Darp.Luau.LuauState state, in global::System.ReadOnlySpan<char> fieldName)
        {
            return fieldName switch
            {
                "level" => global::Darp.Luau.LuauReturnSingle.Ok(self.Level),
                _ => global::Darp.Luau.LuauReturnSingle.NotHandled,
            };
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
        public static global::Darp.Luau.LuauOutcome OnSetIndex(global::@event.@class self, global::Darp.Luau.LuauArgsSingle args, in global::System.ReadOnlySpan<char> fieldName)
        {
            switch (fieldName)
            {
                case "level":
                {
                    if (!args.TryReadNumber(out double valueRaw, out string? error))
                        return global::Darp.Luau.LuauOutcome.Error(error);
                    int value = (int)valueRaw;
                    self.Level = value;
                    return global::Darp.Luau.LuauOutcome.Ok();
                }
                default:
                    return global::Darp.Luau.LuauOutcome.NotHandledError;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
        public static global::Darp.Luau.LuauReturn OnMethodCall(global::@event.@class self, global::Darp.Luau.LuauArgs args, in global::System.ReadOnlySpan<char> methodName) => global::Darp.Luau.LuauReturn.NotHandledError;
    }
}
