//HintName: Player.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Player : global::Darp.Luau.ILuauUserdata<global::Player>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::Player>.Register(global::Darp.Luau.LuauUserdataRegistry<global::Player> registry)
    {
        registry.TypeName = "Player";
        registry.AddMethod("load", static (self, args) =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
            if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            return awaiter.Await(
                new global::System.Threading.Tasks.ValueTask<string?>(self.LoadAsync(args.CancellationToken, a1)),
                static returns => global::Darp.Luau.LuauReturn.Ok(returns)
            );
        });
        registry.AddMethod("save", static (self, args) =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            return awaiter.Await(new global::System.Threading.Tasks.ValueTask(self.SaveAsync(args.CancellationToken)));
        });
        registry.AddMethod("stats", static (self, args) =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out int a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            return awaiter.Await(
                self.GetStatsAsync(a1),
                static returns => global::Darp.Luau.LuauReturn.Ok(returns.Item1, returns.Item2 is null ? default(global::Darp.Luau.IntoLuau) : global::Darp.Luau.IntoLuau.FromUserdata(returns.Item2))
            );
        });
    }
}
