//HintName: Player.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Player : global::Darp.Luau.ILuauUserData<global::Player>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauReturnSingle OnIndex(global::Player self, in global::Darp.Luau.LuauState state, in global::System.ReadOnlySpan<char> fieldName) => global::Darp.Luau.LuauReturnSingle.NotHandled;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauOutcome OnSetIndex(global::Player self, global::Darp.Luau.LuauArgsSingle args, in global::System.ReadOnlySpan<char> fieldName) => global::Darp.Luau.LuauOutcome.NotHandledError;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauReturn OnMethodCall(global::Player self, global::Darp.Luau.LuauArgs args, in global::System.ReadOnlySpan<char> methodName)
    {
        switch (methodName)
        {
            case "load":
            {
                if (!args.TryValidateArgumentCount(1, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
                if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                return awaiter.Await(
                    new global::System.Threading.Tasks.ValueTask<string?>(self.LoadAsync(args.CancellationToken, a1)),
                    static returns => global::Darp.Luau.LuauReturn.Ok(returns)
                );
            }
            case "save":
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                return awaiter.Await(new global::System.Threading.Tasks.ValueTask(self.SaveAsync(args.CancellationToken)));
            }
            case "stats":
            {
                if (!args.TryValidateArgumentCount(1, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 1, out int a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryGetAwaiter(out global::Darp.Luau.LuauAwaiter awaiter, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                return awaiter.Await(
                    self.GetStatsAsync(a1),
                    static returns => global::Darp.Luau.LuauReturn.Ok(returns.Item1, returns.Item2 is null ? default(global::Darp.Luau.IntoLuau) : global::Darp.Luau.IntoLuau.FromUserdata(returns.Item2))
                );
            }
            default:
                return global::Darp.Luau.LuauReturn.NotHandledError;
        }
    }
}
