//HintName: HeroCard.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class HeroCard : global::Darp.Luau.ILuauUserdata<global::HeroCard>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    static void global::Darp.Luau.ILuauUserdata<global::HeroCard>.Register(global::Darp.Luau.LuauUserdataRegistry<global::HeroCard> registry)
    {
        registry.TypeName = "HeroCard";
        registry.AddGetter("name", static (self, _) => global::Darp.Luau.LuauReturnSingle.Ok(self.Name));
        registry.AddSetter("name", static (self, args) =>
        {
            if (!args.TryReadUtf8String(out string? value, out string? error))
                return global::Darp.Luau.LuauOutcome.Error(error);
            self.Name = value;
            return global::Darp.Luau.LuauOutcome.Ok();
        });
    }
}
